#!/bin/bash

file=/vagrant/chumma2

echo "Enter the name and once you are done type exit and press enter"

while true; do
	read -p "Enter the service name: " service
	if [ "$service" = "exit" ]
	then
		echo "Exiting the operation"
		break
	else
		echo "$service" >> /vagrant/chumma2
		echo "Appended $service to /vagrant/chumma2"
	fi
done	
